#!/bin/bash
LOCAL_SOURCE_DIR=/tmp/src


echo "---> Installing application source..."

# apps files
if [ -d $LOCAL_SOURCE_DIR/webapps ]; then
  echo "Copying Application files from webapps of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/webapps/* $CATALINA_HOME/webapps/
fi

# configuration files
if [ -d $LOCAL_SOURCE_DIR/conf ]; then
  echo "Copying config files from conf of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/conf/* $CATALINA_HOME/conf/
fi

# shared lib jar files
if [ -d $LOCAL_SOURCE_DIR/lib ]; then
  echo "Copying Library Jar files from lib of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/lib/* $CATALINA_HOME/lib/
fi

# JAVA Options setenv.sh
if [ -d $LOCAL_SOURCE_DIR/bin ]; then
  echo "Copying JAVA options..."
  cp -Rf $LOCAL_SOURCE_DIR/bin/* $CATALINA_HOME/bin/
fi
